- name: Disable systemd-resolved
  systemd: name=systemd-resolved state=stopped enabled=no

- name: Reconfigure NetworkManager for dnsmasq
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: dnsmasq

- name: dnsmasq.d conf
  copy:
    src: "{{ item }}"
    dest: /etc/NetworkManager/dnsmasq.d/{{ item }}
  loop:
    - local.conf
    - docker-bridge.conf

- name: Reload NetworkManager
  systemd: name=network-manager state=reloaded