- name: Install msmtp
  apt:
    name:
      - msmtp
      - msmtp-mta

- name: Copy msmtp config file
  copy:
    src: /usr/share/doc/msmtp/examples/msmtprc-system.example
    dest: /etc/msmtprc
    mode: '0644'

- name: Fix host in msmtp config
  replace:
    path: /etc/msmtprc
    regexp: 'host mail\.oursite\.example'
    replace: 'host 127.0.0.1'

- name: Fix port in msmtp config
  replace:
    path: /etc/msmtprc
    regexp: 'port 465'
    replace: 'port 25'

- name: Turn off tls in msmtp config
  replace:
    path: /etc/msmtprc
    regexp: 'tls on'
    replace: 'tls off'

- name: Mailhog Docker Container
  docker_container:
    name: mailhog
    image: mailhog/mailhog
    restart_policy: always
    container_default_behavior: no_defaults
    detach: yes
    auto_remove: no
    published_ports:
      - 127.0.0.1:25:1025
      - 127.0.0.1:8025:8025
