- name: Install msmtp
  apt:
    name:
      - msmtp
      - msmtp-mta

- name: Copy msmtp config file
  copy:
    src: /usr/share/doc/msmtp/examples/msmtprc-system.example
    dest: /etc/msmtprc
    mode: '0644'

- name: Fix host in msmtp config
  replace:
    path: /etc/msmtprc
    regexp: 'host mailhub\.oursite\.example'
    replace: 'host 127.0.0.1'

- name: Fix port in msmtp config
  replace:
    path: /etc/msmtprc
    regexp: 'port 465'
    replace: 'port 1025'

- name: Turn off tls in msmtp config
  replace:
    path: /etc/msmtprc
    regexp: 'tls on'
    replace: 'tls off'

- name: Install mailhog
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64
    dest: /usr/local/bin/mailhog
    checksum: sha256:ba921e04438e176c474d533447ae64707ffcdd1230f0153f86cb188d348f25c0
    mode: '0755'

- name: Mailhog systemd unit
  copy:
    src: mailhog.service
    dest: /lib/systemd/system/mailhog.service

- name: Mailhog config
  copy:
    src: mailhog.json
    dest: /etc/mailhog.json

- name: Enable mailhog service
  systemd:
    name: mailhog
    daemon_reload: yes
    enabled: yes
    state: started
