---
- import_tasks: apache.yml
- import_tasks: php.yml
- import_tasks: email.yml
- import_tasks: dnsmasq.yml
- import_tasks: mkcert.yml
- import_tasks: mysql.yml

- name: Update sysctl
  copy:
    src: sysctl-local.conf
    dest: /etc/sysctl.d/local.conf
