- name: Install mkcert
  get_url:
    url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64
    dest: /usr/local/bin/mkcert
    checksum: sha256:e116543bfabb4d88010dda8a551a5d01abbdf9b4f2c949c044b862365038f632
    mode: '0755'
