- name: MySQL Docker Volume
  docker_volume: volume_name=mysql-data

- name: MySQL socket directory
  file:
    path: /var/run/mysqld
    owner: 999
    group: 999
    state: directory
    mode: "0755"

- name: MySQL Docker Container
  docker_container:
    name: mysql-server
    image: mysql:5.7
    restart_policy: always
    container_default_behavior: no_defaults
    detach: yes
    auto_remove: no
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - /var/run/mysqld:/var/run/mysqld:rw
    published_ports:
      - 127.0.0.1:3306:3306
    env:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
