- name: Sury Key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: B188E2B695BD4743

- name: Microsoft Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: PHP Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.sury.org/php buster main
    filename: php

- name: Microsoft Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main
    filename: mssql-release

- name: Microsoft Debconf
  debconf:
    name: msodbcsql17
    question: msodbcsql/ACCEPT_EULA
    vtype: boolean
    value: "true"

- name: Install PHP Packages
  apt:
    name:
      - php7.3-cli
      - php7.3-fpm
      - php7.3-dev
      - php7.3-pgsql
      - php7.3-sqlite3
      - php7.3-gd
      - php7.3-curl
      - php7.3-imap
      - php7.3-mysql
      - php7.3-mbstring
      - php7.3-xml
      - php7.3-zip
      - php7.3-bcmath
      - php7.3-soap
      - php7.3-intl
      - php7.3-readline
      - php7.3-ldap
      - php7.3-sybase
      - php5.6-cli
      - php5.6-fpm
      - php5.6-dev
      - php5.6-pgsql
      - php5.6-sqlite3
      - php5.6-gd
      - php5.6-curl
      - php5.6-imap
      - php5.6-mysql
      - php5.6-mbstring
      - php5.6-xml
      - php5.6-zip
      - php5.6-bcmath
      - php5.6-soap
      - php5.6-intl
      - php5.6-readline
      - php5.6-mcrypt
      - php5.6-ldap
      - php5.6-sybase
      - php-memcached
      - php-apcu
      - php-xdebug
      - php-pear
      - php-imagick
      - imagemagick
      - msodbcsql17
      - mssql-tools
      - unixodbc-dev
      - libmcrypt-dev
      - build-essential
  register: aptphp
  environment:
    ACCEPT_EULA: "Y"

- name: Update php alternative
  alternatives:
    name: php
    path: /usr/bin/php7.3

- name: Update php-config alternative
  alternatives:
    name: php-config
    path: /usr/bin/php-config7.3

- name: Update phpize alternative
  alternatives:
    name: phpize
    path: /usr/bin/phpize7.3

- name: Enable PHP Apache conf
  command: a2enconf php7.3-fpm

- name: Install Pecl modules
  pear:
    name: "pecl/{{ item }}"
    state: latest
  loop:
    - sqlsrv
    - pdo_sqlsrv
    - mcrypt
  register: pecl

- name: Create Pecl ini files
  ini_file:
    path: /etc/php/7.3/mods-available/{{ item }}.ini
    section: "{{ item }}"
    option: extension
    value: "{{ item }}.so"
  loop:
    - sqlsrv
    - pdo_sqlsrv
    - mcrypt

- name: Enable PHP Apache conf
  command: phpenmod -v 7.3 {{ item }}
  loop:
    - sqlsrv
    - pdo_sqlsrv
    - mcrypt

- name: Create Log directory
  file:
    path: /var/log/php
    owner: www-data
    group: adm
    state: directory
    mode: "0750"

- name: Update PHP FPM Pool
  ini_file:
    path: /etc/php/{{ item.version }}/fpm/pool.d/www.conf
    section: "www"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - {version: 5.6, option: "env[APPLICATION_ENVIRONMENT]", value: "development"}
    - {version: 7.3, option: "env[APPLICATION_ENVIRONMENT]", value: "development"}

- name: Add PHP config
  copy:
    src: gwaz.ini
    dest: /etc/php/{{ item }}/mods-available/gwaz.ini
  loop:
    - 5.6
    - 7.3
  when: aptphp.changed

- name: Edit xdebug.ini
  ini_file:
    path: /etc/php/{{ item.version }}/mods-available/xdebug.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - {version: 5.6, section: "xdebug", option: "xdebug.remote_enable", value: "1"}
    - {version: 5.6, section: "xdebug", option: "xdebug.remote_connect_back", value: "1"}
    - {version: 5.6, section: "xdebug", option: "xdebug.remote_port", value: "9000"}
    - {version: 5.6, section: "xdebug", option: "xdebug.max_nesting_level", value: "512"}
    - {version: 7.3, section: "xdebug", option: "xdebug.remote_enable", value: "1"}
    - {version: 7.3, section: "xdebug", option: "xdebug.remote_connect_back", value: "1"}
    - {version: 7.3, section: "xdebug", option: "xdebug.remote_port", value: "9000"}
    - {version: 7.3, section: "xdebug", option: "xdebug.max_nesting_level", value: "512"}
  when: aptphp.changed

- name: Set php_executable variable to a default if not defined
  set_fact:
    php_executable: /usr/bin/php
  when: php_executable is not defined

- name: Check if Composer is installed
  stat: "path={{ composer_bin }}"
  register: composer_bin

- name: Get Composer installer signature
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer
  command: >
    {{ php_executable }} composer-installer.php --filename=composer --install-dir={{ local_bin }} {% if composer_version %} --version={{ composer_version }}{% endif %}
    chdir=/tmp
  when: not composer_bin.stat.exists

- name: Restart PHP
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - php5.6-fpm
    - php7.3-fpm
  when: aptphp.changed or pecl.changed

- name: Restart Apache
  systemd:
    name: apache2
    state: restarted
  when: aptphp.changed
