- hosts: localhost
  vars_files:
    - .env.yml
    - global_vars.yml
  pre_tasks:
    - name: Update Repositories
      apt:
        update_cache: yes
      changed_when: False
      become: yes
  roles:
    - {role: "kerberos", tags: "kerberos", become: yes}
    - {role: "system-level", tags: "system-level", become: yes}
    - {role: "dev-environment", tags: "dev-environment", become: yes}
    - role: gantsign.oh-my-zsh
      tags: oh-my-zsh
      users:
        - username: "{{ ansible_env.USER }}"
          oh_my_zsh:
            theme: agnoster
            plugins: ["git", "aws", "docker", "npm", "pip", "python", "hub"]
    - {role: "user-stuff", tags: "user-stuff"}
