- hosts: localhost
  vars_files:
    - .env.yml
    - global_vars.yml
  pre_tasks:
    - name: Update Repositories
      apt:
        update_cache: yes
      changed_when: False
      become: yes
  roles:
    - {role: "general-packages", tags: "general-packages", become: yes}
#    - {role: "kerberos", tags: "kerberos", become: yes}
    - {role: "dev-environment", tags: "dev-environment", become: yes}
    - {role: "user-stuff", tags: "user-stuff"}
    - role: gantsign.oh-my-zsh
      tags: oh-my-zsh
      users:
        - username: "{{ ansible_env.USER }}"
          oh_my_zsh:
            theme: agnoster
            plugins:
              - git
              - aws
              - docker
              - npm
              - pip
              - python
