- hosts: all
  become: true
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yaml
    - include: tasks/packages.yaml
    - include: tasks/cron.yaml
    - include: tasks/dconf.yaml
