- name: Install flatpak
  apt:
    name: flatpak

- name: Add Flatpak remote
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: New flatpak.sh profile.d
  copy:
    src: flatpak.sh
    dest: /etc/profile.d/flatpak.sh

- name: Install Flatpaks
  flatpak:
    name: "{{ item }}"
  loop:
      - io.github.Pithos
      - org.remmina.Remmina
      - org.gnome.meld
