- import_tasks: flatpak.yml
- import_tasks: disable-services.yml

- name: Docker Key
  apt_key:
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    url: https://download.docker.com/linux/debian/gpg

- name: VirtualBox Key
  apt_key:
    id: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    filename: docker

- name: VirtualBox Repo
  apt_repository:
    repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian buster contrib
    filename: virtualbox

- name: Check if Chrome installed
  stat: 
    path: /etc/apt/sources.list.d/google-chrome.list
  register: chrome

- name: Install Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: not chrome.stat.exists

- name: Check if Teamviewer installed
  stat: 
    path: /etc/apt/sources.list.d/teamviewer.list
  register: teamviewer

- name: Install Teamviewer
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  when: not teamviewer.stat.exists

- name: Install Packages
  apt:
    name:
      - htop
      - dconf-editor
      - dconf-cli
      - docker-ce
#      - virtualbox-6.0
      - fonts-powerline
      - anacron
      - telnet
      - tcpdump
      - ruby
      - ruby-dev
      - inotify-tools
      - moreutils
      - locate

- name: Source Code Pro fonts
  git:
    depth: 1
    dest: /usr/share/fonts/opentype/scp
    repo: https://github.com/adobe-fonts/source-code-pro.git
    refspec: refs/heads/release
  register: scp

- name: Rebuild font-cache
  command: fc-cache -f -v
  when: scp.changed
