alias pwsh="docker run --rm -e DISPLAY=:1 -v "${XDG_RUNTIME_DIR}/xdg-open-server:/run/user/0/xdg-open-server:ro" -v /usr/share/xdg-open-server/xdg-open.sh:/usr/bin/xdg-open:ro -v /usr/bin/socat:/usr/bin/socat -v $HOME:$HOME -v $HOME/.local/share/powershell/:/root/.local/share/powershell/ -v $HOME/.cache/powershell/:/root/.cache/powershell/ -it mcr.microsoft.com/azure-powershell pwsh"
alias mysql="docker run --rm -it -v /var/run/mysqld:/var/run/mysqld mysql:5.7 mysql"
alias mysqldump="docker run --rm -it -v /var/run/mysqld:/var/run/mysqld mysql:5.7 mysqldump"
alias mysqladmin="docker run --rm -it -v /var/run/mysqld:/var/run/mysqld mysql:5.7 mysqladmin"
alias ll="ls -lav --group-directories-first"
alias service="systemctl"
alias uservice="systemctl --user"
alias mitmproxy="docker run --rm -it -v mitmproxy-data:/home/mitmproxy/.mitmproxy -p 8888:8080 mitmproxy/mitmproxy:latest"
alias mitmdump="docker run --rm -it -v mitmproxy-data:/home/mitmproxy/.mitmproxy -p 8888:8080 mitmproxy/mitmproxy:latest mitmdump"
