
- name: Docker Key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- name: VirtualBox Key
  apt_key:
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    filename: docker

- name: VirtualBox Repo
  apt_repository:
    repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian buster contrib
    filename: virtualbox

- name: Check for Chrome
  stat: 
    path: /etc/apt/sources.list.d/google-chrome.list
  register: chrome

- name: Install Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: not chrome.stat.exists

- name: Check for Teamviewer
  stat: 
    path: /etc/apt/sources.list.d/teamviewer.list
  register: teamviewer

- name: Install Teamviewer
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  when: not teamviewer.stat.exists

- name: Check for Discord
  stat: 
    path: /usr/bin/discord
  register: discord

- name: Install Discord
  apt:
    deb: https://discord.com/api/download?platform=linux&format=deb
  when: not discord.stat.exists

- name: Install Packages
  apt:
    name:
      - htop
      - dconf-editor
      - dconf-cli
      - docker-ce
      - virtualbox-6.1
      - fonts-powerline
      - anacron
      - telnet
      - tcpdump
      - ruby
      - ruby-dev
      - inotify-tools
      - moreutils
      - locate

- name: Uninstall Packages
  apt:
    name:
      - xserver-xorg-video-nouveau
    autoremove: yes
    purge: yes
    state: absent

- name: Buster Backports
  apt_repository:
    repo: deb https://deb.debian.org/debian buster-backports main contrib non-free
    filename: buster-backports

- name: Install nvidia stuff
  apt:
    name: 
      - nvidia-driver
      - nvidia-settings
      - nvidia-smi
      - nvidia-kernel-dkms
    default_release: buster-backports

- name: nvidia xorg conf
  copy:
    content: |
      Section "ServerLayout"
        Identifier "layout"
        Option "AllowNVIDIAGPUScreens"
      EndSection
    dest: /etc/X11/xorg.conf.d/00-nvidia.conf
    mode: 0644
