
- name: Docker Key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: VirtualBox Key
  apt_key:
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    filename: docker
  when: ansible_facts['distribution'] == 'Deepin'

- name: Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    filename: docker
  when: ansible_facts['distribution'] != 'Deepin'

- name: VirtualBox Repo
  apt_repository:
    repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian buster contrib
    filename: virtualbox
  when: ansible_facts['distribution'] == 'Deepin'

- name: VirtualBox Repo
  apt_repository:
    repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib
    filename: virtualbox
  when: ansible_facts['distribution'] != 'Deepin'

- name: Check for Chrome
  stat: path=/etc/apt/sources.list.d/google-chrome.list
  register: chrome

- name: Install Chrome
  apt: deb=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: not chrome.stat.exists

- name: Timeshift Repo
  apt_repository: repo=ppa:teejee2008/timeshift

- name: Install Packages
  apt:
    name:
      - htop
      - docker-ce
      - virtualbox-6.1
      - fonts-powerline
      - tcpdump
      - locate
      - nmap
      - telnet
      - network-manager-l2tp-gnome
      - network-manager-openconnect-gnome
      - timeshift
