- name: Create systemd directory
  file: path=~{{ user }}/.config/systemd/user/ state=directory mode=0755

- name: Copy systemctl services
  copy:
    src: "{{ item }}"
    dest: ~{{ user }}/.config/systemd/user/
  loop:
    - ansible.timer
    - logrotate.service
    - logrotate.timer
    - flatpak-update.service
    - flatpak-update.timer

- name: Ansible service
  template: src=ansible.service.j2 dest=~{{ user }}/.config/systemd/user/ansible.service mode=0644

- name: Enable timers
  systemd:
    name: "{{ item }}.timer"
    daemon_reload: yes
    enabled: yes
    state: started
    scope: user
  loop:
    - logrotate
    - ansible
    - flatpak-update
