- name: Install flatpak
  apt: name=flatpak
  become: yes

- name: Add Flatpak remote
  flatpak_remote: name=flathub flatpakrepo_url=https://dl.flathub.org/repo/flathub.flatpakrepo method=user

- name: Install Flatpaks
  flatpak: name={{ item }} method=user
  loop:
    - io.github.Pithos
    - com.discordapp.Discord
    - org.remmina.Remmina
    - org.gnome.meld
    - com.getpostman.Postman
    - org.gimp.GIMP
    - com.sublimetext.three
    - com.toggl.TogglDesktop
    - com.axosoft.GitKraken
    - org.inkscape.Inkscape
    - org.filezillaproject.Filezilla
    - com.transmissionbt.Transmission
    - com.todoist.Todoist
    - com.slack.Slack
    - us.zoom.Zoom