- name: Download Jetbrains Toolbox
  unarchive:
    src: https://data.services.jetbrains.com/products/download?platform=linux&code=TBA
    dest: /tmp
    creates: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
    remote_src: yes
  register: "jetbrains_toolbox"

- name: Get Jetbrains Toolbox dir
  find:
    path: /tmp
    file_type: directory
    pattern: jetbrains*
  register: jetbrains_dir
  when: jetbrains_toolbox.changed

- name: Move Jetbrains Toolbox to local bin
  command: './jetbrains-toolbox --minimize'
  args:
    chdir: "{{ jetbrains_dir.files[0].path }}"
  when: jetbrains_toolbox.changed
