- name: Install nvm
  shell: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    creates: "~{{ user }}/.nvm/nvm.sh"
    warn: false

- name: Install latest node
  shell: "nvm install --lts --latest-npm"
  args:
    creates: "~{{ user }}/.nvm/versions/node"
    warn: false
    executable: /bin/bash
