- name: Check if {{ tool.package }} installed
  stat: path={{ tool.dir }}/composer.lock
  register: composer

- name: Install {{ tool.package }}
  when: not composer.stat.exists
  block:
    - name: Create {{ tool.package }} directory
      file: path={{ tool.dir }} state=directory mode=0755

    - name: Install {{ tool.package }}
      composer: command=require arguments={{ tool.package }} working_dir={{ tool.dir }}

    - name: Link {{ tool.package }}
      file: src={{ tool.dir }}/vendor/bin/{{ item }} dest={{ local_bin }}/{{ item }} state=link
      loop: "{{ tool.bin }}"
