- import_tasks: hub.yml
- import_tasks: tmate.yml

- include_tasks: php-tools.yml
  loop:
    - {package: "squizlabs/php_codesniffer", dir: "{{ php_tool_dir }}/phpcs", bin: ["phpcs"]}
    - {package: "friendsofphp/php-cs-fixer", dir: "{{ php_tool_dir }}/php-cs-fixer", bin: ["php-cs-fixer"]}
    - {package: "phploc/phploc", dir: "{{ php_tool_dir }}/phploc", bin: ["phploc"]}
    - {package: "phpmd/phpmd", dir: "{{ php_tool_dir }}/phpmd", bin: ["phpmd"]}
    - {package: "psy/psysh", dir: "{{ php_tool_dir }}/psysh", bin: ["psysh"]}
  loop_control:
    loop_var: tool

- include_tasks: python-tools.yml
  loop:
    - {py_version: 3.8, packages: ["httpie"], dir: "{{ python_tool_dir }}/httpie", bin: ["http"]}
    - {py_version: 3.8, packages: ["speedtest-cli"], dir: "{{ python_tool_dir }}/speedtest", bin: ["speedtest-cli"]}
    - {py_version: 3.8, packages: ["awscli", "awsebcli", "aws-shell"], dir: "{{ python_tool_dir }}/aws", bin: ["aws", "aws_completer", "aws_zsh_completer.sh", "aws-shell", "eb"]}
    - {py_version: 3.8, packages: ["docker-compose"], dir: "{{ python_tool_dir }}/docker-compose", bin: ["docker-compose"]}
    - {py_version: 3.8, packages: ["undervolt"], dir: "{{ python_tool_dir }}/undervolt", bin: ["undervolt"]}
  loop_control:
    loop_var: tool

- include_tasks: undervolt.yml
  args:
    apply:
      become: true

- name: Install saml2aws
  unarchive:
    src: https://github.com/Versent/saml2aws/releases/download/v2.27.0/saml2aws_2.27.0_linux_amd64.tar.gz
    dest: "{{ local_bin }}"
    creates: "{{ local_bin }}/saml2aws"
    remote_src: yes

- name: Install Etcher
  get_url:
    url: https://github.com/balena-io/etcher/releases/download/v1.5.108/balenaEtcher-1.5.108-x64.AppImage
    dest: "{{ local_bin }}/etcher"
    mode: "0755"
    checksum: sha512:774331a2954cf97d76916ff886659a126e6975ff4b4e5f237ee0ad499e476688fc352d0af0c442f6f827ee0ee660020a74f521baf124b169d427c3f0dd3c22f8

- name: Install drone cli
  unarchive:
    src: https://github.com/drone/drone-cli/releases/download/v1.2.2/drone_linux_amd64.tar.gz
    dest: "{{ local_bin }}"
    creates: "{{ local_bin }}/drone"
    remote_src: yes

- name: AWS Docker Credential Helper
  get_url:
    url: https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.4.0/linux-amd64/docker-credential-ecr-login
    dest: "{{ local_bin }}/docker-credential-ecr-login"
    checksum: sha256:https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.4.0/linux-amd64/docker-credential-ecr-login.sha256
    mode: "0755"
